###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.
# Create new hashed password: docker run authelia/authelia:latest authelia hash-password <new_password>
# https://docs.authelia.com/configuration/authentication/file.html

# List of users
users:
  john:
    displayname: JohnDoe
    password: "$argon2id$v=19$m=65536,t=3,p=4$Hjc8e7WYcBFcJmEDUOsS9A$ozM7RyZR1EyDR8cuyVpDDfmLrGPGFgo5E2NNqRumui4"
    email: john@example.com
    groups:
      - admins
      - dev