---
- name: Delete cloud-init packages to the latest version
  apt:
    name: cloud-init
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name:  touch cloud-init.disabled
  shell: >
      touch /etc/cloud/cloud-init.disabled

- name:  swapoff
  shell: >
      swapoff --all

- name: Check if auto update is enabled
  stat:
    path: /etc/apt/apt.conf.d/20auto-upgrades
  register: autoupdate

- name: Disable auto update
  when: autoupdate.stat.exists
  file:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent

- name: Wait for any possibly running unattended upgrade to finish
  when: autoupdate.stat.exists
  raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: true
    update_cache: yes

- name: Reboot host(s) after package upgrade
  shell: sleep 2 && /sbin/shutdown -r now "ansible reboot request"
  async: 1
  poll: 0
  ignore_errors: true
  when: inventory_hostname != "127.0.0.1" and inventory_hostname != "localhost"

- name: Waiting for host(s) to reboot
  local_action: "wait_for host={{inventory_hostname}} port=22 state=started delay=60"
  when: inventory_hostname != "127.0.0.1" and inventory_hostname != "localhost"

- name: Verify system dependencies
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - apache2-utils
      - tree
      - wget 
      - curl
      - tcpdump
      - python3-docker
      - ntp
    state: latest
    force_apt_get: true
    update_cache: yes