---
- name: install glusterfs client
  apt:
    name: glusterfs-client
    state: present

- name: make glusterfs mount dir
  file:
    path: "/mnt/{{ gluster_volume_name }}"
    state: directory

- name: mount glusterfs volume gfs
  mount:
    name: /mnt/gfs
    src: "{{ groups.gluster_nodes[0] }}:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted