---
- name: Create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  template:
    src: whoami.j2
    dest: /home/{{ansible_user}}/stacks/whoami-stack.yml
    mode: 0775
    force: true

- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  docker_stack:
    state: present
    name: whoami
    prune: true
    with_registry_auth: true
    compose:
      - /home/{{ansible_user}}/stacks/whoami-stack.yml