- name: Update apt packages
  apt:
    upgrade: yes
    update_cache: yes
  tags: docker

- name: Install Docker Dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  tags: docker

- name: Get Docker key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker

- name: Add Docker packages to Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release|lower }} stable
  tags: docker

- name: Install Docker 
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
  tags: docker

- name: Appending the group docker 
  user:
    name: ubuntu
    groups: docker
    append: yes